### ISSUE TITLE
[Epic] 개발 환경 셋팅

### ISSUE THREAD

**Issue by haesoo-y** [YoonsProjects/SwitchStory#11]
### 에픽 내용
> 에픽 내용을 자세히 적어주세요
- 백엔드 기초 개발 환경 셋팅
- 프론트 기초 개발 환경 셋팅

### 참고 사항
> 이미지, 코드 또는 참고 내용
- 

### 예상 테스크
- [ ] 백엔드 Nest 구조 셋팅
- [ ] 백엔드 필요 모듈 설치
- [ ] 프론트 React 구조 셋팅
- [ ] 프론트 필요 모듈 설치
- [ ] 프론트 StoryBook 추가
- [ ] 리드미 내용 업데이트

### 관련 사항
- 문서 : 
- 링크 :
